- name: add diamond user
  user: name=diamond state=present system=yes createhome=no

- name: diamond install
  pip: name=diamond state=present

- name: copy diamond systemd config
  template: src=diamond.service.j2 dest=/etc/systemd/system/diamond.service
  notify: 
    - update systemd
    - restart diamond

- name: create diamond directories
  file: path={{ item }} state=directory owner=diamond group=diamond 
  with_items:
    - /etc/diamond
    - /etc/diamond/handlers
    - /etc/diamond/collectors
    - /var/log/diamond
    
- name: copy diamond config
  template: src=diamond.conf.j2 dest=/etc/diamond/diamond.conf
  notify: restart diamond

- name: copy diamond GraphiteHandler config
  template: src=GraphiteHandler.conf.j2 dest=/etc/diamond/handlers/GraphiteHandler.conf
  notify: restart diamond

- name: copy diamond CPUCollector config
  template: src=collectors/CPUCollector.conf.j2 dest=/etc/diamond/collectors/CPUCollector.conf
  notify: restart diamond

- name: copy diamond DiskSpaceCollector config
  template: src=collectors/DiskSpaceCollector.conf.j2 dest=/etc/diamond/collectors/DiskSpaceCollector.conf
  notify: restart diamond

- name: copy diamond DiskUsageCollector config
  template: src=collectors/DiskUsageCollector.conf.j2 dest=/etc/diamond/collectors/DiskUsageCollector.conf
  notify: restart diamond

- name: copy diamond MemoryCollector config
  template: src=collectors/MemoryCollector.conf.j2 dest=/etc/diamond/collectors/MemoryCollector.conf
  notify: restart diamond

- name: copy diamond NetworkCollector config
  template: src=collectors/NetworkCollector.conf.j2 dest=/etc/diamond/collectors/NetworkCollector.conf
  notify: restart diamond

- name: copy diamond LoadAverageCollector config
  template: src=collectors/LoadAverageCollector.conf.j2 dest=/etc/diamond/collectors/LoadAverageCollector.conf
  notify: restart diamond

- name: copy diamond UptimeCollector config
  template: src=collectors/UptimeCollector.conf.j2 dest=/etc/diamond/collectors/UptimeCollector.conf
  notify: restart diamond

- name: be sure owns /var/log/diamond
  file: path=/var/log/diamond state=directory recurse=yes owner=diamond group=diamond

- name: be sure diamond is running and enabled
  service: name=diamond state=started enabled=yes
