- name: restart firewalld
  service: name=firewalld state=restarted

- name: reload firewalld
  command: firewall-cmd --reload

- name: update systemd
  command: /usr/bin/systemctl daemon-reload

- name: reload nginx
  service: name=nginx state=reloaded
